name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Resources
        uses: actions/checkout@v2

      - name: .env 환경 변수 동적 생성
        run: |
          echo "${{ secrets.CLIENT_ENV }}" > .env
          pwd
          ls -al

      - name: nodejs install
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: npm install
        run: npm install

      - name: npm run build (Vite)
        run: |
          npm run build
          ls -al ./dist  # dist 폴더가 생성되었는지 확인

      # build EC2 업로드
      - name: EC2에 빌드된 파일/폴더 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./dist/*" # 기존 build → dist 변경
          target: "/home/ubuntu/client"

      - name: SSH로 EC2에 접속 후 서버 재시작
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/client/* /var/www/html/  # 기존 build → client로 변경
            sudo systemctl restart nginx
            sudo rm -rf /home/ubuntu/client
            ls -al /var/www/html  # 배포된 파일 확인
