name: Deploy React (Vite) with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        run: |
          npm install
          npm run build
          docker build -t my-vite-app .
          docker save my-vite-app | gzip > my-vite-app.tar.gz

      - name: Copy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "my-vite-app.tar.gz"
          target: "~/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 기존 컨테이너 중지 및 삭제 (포트 충돌 방지)
            sudo docker stop my-vite-app || true
            sudo docker rm my-vite-app || true

            # 기존 이미지 삭제 (중복 방지)
            sudo docker rmi my-vite-app || true

            # 새로운 Docker 이미지 로드 및 실행
            sudo docker load < my-vite-app.tar.gz
            sudo docker run -d --name my-vite-app -p 80:80 my-vite-app
